### ISSUE TITLE
The extension will grab mouse and do not release for ever.

### ISSUE THREAD

**Issue by linkycj** [bsaleil/todolist-gnome-shell-extension#23]
I got the newest version code to test.
When I removed all task, and want to add new task, the mouse had been grabbed. 
Other gnome application could not recieve the mouse event.
After comment the follow lines, everything is ok.
<pre>
                /*
                // Add keybinding
                global.display.add_keybinding
                (
                        key_open,
                        mySettings,
                        Meta.KeyBindingFlags.NONE,
                        Lang.bind(this, function() { this.menu.open(); })
                );
                
                // Auto focus
                this.menu.connect('open-state-changed', Lang.bind(this, function(menu, open)
                {
                        if (open) { this.newTask.grab_key_focus(); }
                        else { this.newTask.get_stage().set_key_focus(null); }
                }));
                */
</pre>

**Comment by bsaleil** [comment]
Sorry for the late answer but it should be fixed now.
