### ISSUE TITLE
Panel label not vertically aligned

### ISSUE THREAD

**Issue by beanaroo** [bsaleil/todolist-gnome-shell-extension#32]
![screenshot from 2014-03-03 14 15 51](https://f.cloud.github.com/assets/1748909/2305891/65676b2e-a271-11e3-98ff-aaa6939f0600.png)

The panel label does not seem to be aligned with the rest of the panel.
This is more evident when using different fonts in the shell theme.

**Comment by bsaleil** [comment]
Added in ff26ab4367f7f92c4114e28dfa6b919a4f377d7a
Thanks.
