### ISSUE TITLE
doesn't work with 3.12

### ISSUE THREAD

**Issue by sindhus** [bsaleil/todolist-gnome-shell-extension#33]
It currently doesn't work with 3.12.
If you could tell me how I can make it work, I'd be glad to help out.

**Comment by googol42** [comment]
Any change this extension is made compatible with gnome 3.14?

**Comment by bsaleil** [comment]
Extension works with 3.14 (see last commit) but you can't install from website for now. Please download from this repository instead.

**Comment by bsaleil** [comment]
If somebody want it to work with 3.12, can you just try to add 3.12 in metadata.json and give feedback ?
