### ISSUE TITLE
Can't create more then 30 tasks

### ISSUE THREAD

**Issue by ndias** [bsaleil/todolist-gnome-shell-extension#34]
After create 30 tasks I can't create more because the box to create task is not visible in my monitor, maybe a up down scroll bar is needed.

**Comment by bsaleil** [comment]
What is your shell / extension version ? 
The scroll bar is working here if the box exceeds screen bounds.

**Comment by ndias** [comment]
Hi,

 I have this problem since Fedora 20, now I'm in Fedora 21 with
gnome-shell-3.14.3 and Version 40 for the TaskBar extension

Cheers,
Nuno

On Fri, 2015-02-20 at 10:48 -0800, bsaleil wrote:
> What is your shell / extension version ? 
> The scroll bar is working here if the box exceeds screen bounds.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

-- 
Nuno Dias <ndias@lip.pt>
LIP

**Comment by bsaleil** [comment]
Can you try the extension from the last commit please ?

cd ~/.local/share/gnome-shell/extensions/
git clone https://github.com/bsaleil/todolist-gnome-shell-extension.git
mv todolist-gnome-shell-extension todolist@bsaleil.org

Then reboot your shell (ALT+F2 and type "r").

**Comment by ndias** [comment]
Ok, with the last commit I have the bar to go down and up when I have
more than 30 tasks, but the buttons to delete/edit/etc  disappeared.

Cheers,
Nuno

On Tue, 2015-02-24 at 14:00 -0800, bsaleil wrote:
> Can you try the extension from the last commit please ?
> 
> cd ~/.local/share/gnome-shell/extensions/
> git clone
> https://github.com/bsaleil/todolist-gnome-shell-extension.git
> mv todolist-gnome-shell-extension todolist@bsaleil.org
> 
> Then reboot your shell (ALT+F2 and type "r"). 
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

-- 
Nuno Dias <ndias@lip.pt>
LIP

**Comment by bsaleil** [comment]
There has never been edit/delete buttons in this extension. I think you reported the bug to the wrong repository.
