### ISSUE TITLE
Support for Gnome 3.16

### ISSUE THREAD

**Issue by googol42** [bsaleil/todolist-gnome-shell-extension#38]
Hello,

can you add support for 3.16?

Regards

**Comment by googol42** [comment]
I added 3.16 to the metadata and it does not work. Seems some work has to be done to make it compatible. Regards

**Comment by bsaleil** [comment]
Yes like with every new version of the shell and it's really annoying.
I'll try to take a look at it as soon as I have time. Feel free to help, thx for report.

**Comment by bsaleil** [comment]
Done with de73b68b88
