### ISSUE TITLE
Edit/Done Button

### ISSUE THREAD

**Issue by malteee** [bsaleil/todolist-gnome-shell-extension#4]
It would be nice if you can make an "Edit" and "Done" Button near the ToDos. So you can klick on the "Done"-Button to Close/Delete the ToDo and on the "Edit" Button to Edit the name of the ToDo!

**Comment by bsaleil** [comment]
I just want to keep this extension as simple as possible.
If you really want more advanced features, take a look at 
https://extensions.gnome.org/extension/570/todotxt/

**Comment by alexeevdv** [comment]
@bsaleil, quick answer :)

**Comment by bsaleil** [comment]
Haha sorry. I have no time to work on the extension for now. I'll try to keep issues updated at least. Feel free to help!
