### ISSUE TITLE
Extension not installed after switch on

### ISSUE THREAD

**Issue by waldyd** [bsaleil/todolist-gnome-shell-extension#40]
Hello,

After switch on the control on https://extensions.gnome.org/extension/162/todo-list/, the extension is not being installed. (fedora 4.2.3-300.fc23.x86_64)

Gnome Version:
- Version: 2.32.0
- Distributor: Red Hat, Inc
- Build Date: 17/06/15

gnome-shell --version
GNOME Shell 3.18.3

**Comment by porjo** [comment]
I'm having the same issue on Fedora 23

**Comment by bsaleil** [comment]
This extension only works with Gnome-Shell <= 3.16.
I have no idea what are the changes of the API from 3.16 to 3.18, and as usual with a new GS version, there may be little code to write or the entire extension to rewrite to support new version.
I do not use Gnome anymore so I can't work on the extension at the moment.

**Comment by ovnicraft** [comment]
I confirm the same issue at Fedora23
Gnome Shell Versión 3.18.2

**Comment by ovnicraft** [comment]
@bsaleil any hint to install manually and debug it ?

**Comment by bsaleil** [comment]
Cloning repo in ~/.local/share/gnome-shell/extensions/ should do the work.
Don't forget to rename the folder  "todolist@bsaleil.org".
Then reload the shell  (type "r" in the window opened when you hit Alt+f2)
The extension should now be available in gnome-tweak-tool.

All warnings and errors messages are available in session log messages. You can read those messages in a distribution using systemd with the **journalctl** command.

**Comment by bsaleil** [comment]
Should be fixed soon for 3.20 (see #41).
The extension seems to work fine with 3.20 without any change (except for metadata).
Can somebody using 3.18 test it by changing only version in metadata ?

**Comment by hm1rafael** [comment]
Using 3.18.5, still not working.

**Comment by bsaleil** [comment]
@hm1rafael, what did you try ? Did you try to change version information in metadata to 3.18 ?

**Comment by jfjallid** [comment]
I followed your instructions to clone & rename the repo, update the metadata to include version 3.22 and reload the shell. After that I could find and enable it it the gnome-tweak-tool extension list and it seems to work perfectly for me :)

**Comment by qmenoret** [comment]
Working great on gnome 3.18.5 when cloning and updating metadata.json manually.

**Comment by davegregg** [comment]
#46 adds the metadata fix for gnome-shell versions 3.18, 3.22, and 3.24

**Comment by pringlized** [comment]
Just tried to install and it failed. I'm Gnome shell 3.24.2 on Arch 4.11.9-1.

I'm getting the following error. Any suggestions before I pop open the hood and trace it down? I've written a simple extension before so my knowledge of the API is very limited.

TypeError: redeclaration of formal parameter iter

Stack trace:
Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
@

:1:49

**Comment by davegregg** [comment]
@pringlized This would be a different problem and solution than the above users were experiencing. I just tested this extension on Gnome Shell 3.24.2 and the error displayed in Looking Glass is `Shell.KeybindingMode is undefined` opening new Issue.

**Comment by pringlized** [comment]
Thanks David!  I'm looking forward to using your extension.  I'll respond
on github over the weekend after I have the chance to get it running.
Thanks for your great work.


--
Jim Pringle
pringlized@gmail.com   |   San Francisco, CA
Phone: 925.640.0661

**Comment by pringlized** [comment]
Thanks Dave!

I followed your instructions and it works like a charm.  Elegant in it's simplicity.  Thanks again.

**Comment by bsaleil** [comment]
Thanks @davegregg, I added the manual installation instructions to the readme
