### ISSUE TITLE
Shell.KeybindingMode is undefined

### ISSUE THREAD

**Issue by davegregg** [bsaleil/todolist-gnome-shell-extension#47]
Extension fails to enable, throwing the error `Shell.KeybindMode is undefined` in Looking Glass. 

Reported by https://github.com/bsaleil/todolist-gnome-shell-extension/issues/40#issuecomment-315487927

I've tested this also on Gnome Shell 3.24.2 -- in my case, I'm running Ubuntu 17.10 alpha (Artful Aardvark) and Wayland.

**Comment by davegregg** [comment]
Oh, nevermind. The problem was fixed in #46 but the Gnome Shell Extension store doesn't have this latest update.

@bsaleil Can you update the version served by Gnome Shell Extension?

**Comment by bsaleil** [comment]
I often have issues when trying to upload a new version to the gnome shell extensions website.
It's probably better to install it from the repo to have an up-to-date version.
