### ISSUE TITLE
Unable to Install in Ubuntu 17.10

### ISSUE THREAD

**Issue by AlisaMaas** [bsaleil/todolist-gnome-shell-extension#51]
Just upgraded to 17.10 and I notice that I get the following error when I try to launch the todo list app:

SyntaxError: redeclaration of formal parameter iter

Stack trace:  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43
  

I have not previously used the todo list app, but it seemed like a handy thing to have, so I'd be interested in giving it a try if/when this is fixed, and would be happy to experiment; I don't have any todo list data to lose.

**Comment by bsaleil** [comment]
Please, try manual installation (https://github.com/bsaleil/todolist-gnome-shell-extension/blob/master/README.md)

**Comment by Battleman** [comment]
Same problem (exactly) with Debian buster. Manual installation did not work. Precisely, it appeared in gnome-tweak-tools but grey and an error. Clicking on the gear only shows the same error as mentioned.
![image](https://user-images.githubusercontent.com/6746316/37287821-fdf78d6c-2605-11e8-86b2-83109078209b.png)
