### ISSUE TITLE
Unable to show in the GNOME Tweak Tool

### ISSUE THREAD

**Issue by jufei** [bsaleil/todolist-gnome-shell-extension#52]
hi:
I installed it with git clone. But it does not appear in the GNOME tweak tool.

My GNOME extension version is: GNOME Shell 3.25.4

Would you please help to check it?

Thanks.

**Comment by kenuan-dev** [comment]
I follow the steps from here: "https://extensions.gnome.org/extension/162/todo-list/" ad now a can not open Gnome Control Center. 

Error: gnome-control-center: error while loading shared libraries: libwebpdemux.so.2: cannot open shared object file: No such file or directory

**Comment by bsaleil** [comment]
@kenuan-dev what's your gnome-shell version ? (`gnome-shell --version`)
