### ISSUE TITLE
Not working in Gnome 3.32

### ISSUE THREAD

**Issue by tiotrom** [bsaleil/todolist-gnome-shell-extension#53]
Like the title says :(

**Comment by bsaleil** [comment]
Should be fixed with the last commit (8696bc6fc4d8e4b0bd72fec6394abce06f3fc056).
Let me know if you have any issue, I'm closing it for now.

**Comment by tiotrom** [comment]
Are you the one updating the changes on https://extensions.gnome.org/extension/570/todotxt/? If not I can make the maintainer aware. Cheers and thank you!

**Comment by bsaleil** [comment]
This is not the same extension.

**Comment by tiotrom** [comment]
Oh sorry wrong link. This https://extensions.gnome.org/extension/162/todo-list/

**Comment by bsaleil** [comment]
Yes I'm the one updating this one :)
I'll upload it asap.
