### ISSUE TITLE
Where does it store its settings?

### ISSUE THREAD

**Issue by tiotrom** [bsaleil/todolist-gnome-shell-extension#54]
Hi, I have full backups of my Linux and today I reinstalled it. But this extenssion's settings are all gone. Where are the settings for it stored? Basically I lose my to-do list :D - cheers!

**Comment by bsaleil** [comment]
Hi, the elements in your todo list are stored in [~/.list.tasks](https://github.com/bsaleil/todolist-gnome-shell-extension/blob/master/extension.js#L49).

**Comment by tiotrom** [comment]
Thanks a bunch! Restored! :)
