### ISSUE TITLE
Gnome 40 support

### ISSUE THREAD

**Issue by bagage** [bsaleil/todolist-gnome-shell-extension#60]
The extension doesn't work on Fedora Gnome 40 unfortunately:

> TypeError: Gtk.HBox is not a constructor

I don't know how much work it'd require to make it work again but I miss the extension :crying_cat_face:.

Cf [migration guide](https://gjs.guide/extensions/upgrading/gnome-shell-40.html)

A basic workaround for now is to delete `prefs.js` (and lose prefs obviously!) - I think the proper way would be to migrate prefs to `.ui` file?

**Comment by rastersoft** [comment]
Just edit ~/.local/share/gnome-shell/extensions/todolist@bsaleil.org/metadata.json   and add "40" (with double quotes) in the "shell-version" field. It will work again.

I'll try to do a patch and send it to the author.

**Comment by bsaleil** [comment]
@rastersoft fixed that in https://github.com/bsaleil/todolist-gnome-shell-extension/pull/61
